# Generated by Django 4.2.16 on 2025-07-09 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.CharField(max_length=100, unique=True)),
                ('patient_email', models.EmailField(max_length=254)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('notified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_id', models.CharField(max_length=100, unique=True)),
                ('patient_email', models.EmailField(max_length=254)),
                ('ready_date', models.DateField()),
                ('medication', models.CharField(max_length=200)),
                ('notified', models.BooleanField(default=False)),
            ],
        ),
    ]
