version: '3.8'

services:
  # === User Service ===
  user_service_db:
    image: postgres:16
    container_name: user_service_db
    restart: always
    environment:
      POSTGRES_DB: user_service_db
      POSTGRES_USER: user_service_user
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - user_service_postgres_data:/var/lib/postgresql/data

  user_service:
    build: ./user_service
    container_name: user_service_app
    ports:
      - "5001:5000"
    depends_on:
      - user_service_db
      - consul
    environment:
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - POSTGRES_DB=user_service_db
      - POSTGRES_USER=user_service_user
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_HOST=user_service_db # Rất quan trọng: trỏ đúng service DB
      - POSTGRES_PORT=5432

  # === Appointment Service ===
  appointment_service_db:
    image: postgres:16
    container_name: appointment_service_db
    restart: always
    environment:
      POSTGRES_DB: appointment_service_db
      POSTGRES_USER: appointment_user
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5433:5432"
    volumes:
      - appointment_service_postgres_data:/var/lib/postgresql/data

  appointment_service:
    build: ./appointment_service
    container_name: appointment_service_app
    ports:
      - "5002:5000"
    depends_on:
      - appointment_service_db
      - consul
    environment:
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - POSTGRES_DB=appointment_service_db
      - POSTGRES_USER=appointment_user
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_HOST=appointment_service_db
      - POSTGRES_PORT=5432

  # === Consul ===
  consul:
    image: consul:1.1.0
    container_name: consul
    ports:
      - "8500:8500"  # Giao diện Web UI
      - "8600:8600/udp"  # DNS server (nếu dùng)
    command: agent -dev -client=0.0.0.0

  # === Resolver Service ===
  resolver_service:
    build: ./resolver_service
    container_name: resolver_service
    ports:
      - "7070:7000"
    environment:
      - ENV=local  # hoặc prod nếu deploy thật

volumes:
  user_service_postgres_data:
  appointment_service_postgres_data:
